version: '3'

services:
  app:
    container_name: introduction-bicep
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - type: bind
        source: .
        target: /src

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    #network_mode: 'host'
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: 'host' #service:db
